language: cpp

os: linux
dist: trusty
sudo: required

addons:
  apt:
    packages:
      - libssl-dev
      - libboost-dev
      - libmagic-dev
      - cmake
      - checkinstall

matrix:
  include:
    - env: "_config=debug_cxx98"
    - env: "_config=debug_cxx11"
    - env: "_config=optimized_debug_cxx98"
    - env: "_config=optimized_debug_cxx11"
    - env: "_config=release_cxx98"
    - env: "_config=release_cxx11"

before_install:
  - "pushd third"
  - "./build_mysql-connector-c_deb.sh"
  - "./build_mongo-c-driver_deb.sh"
  - "popd"

install:
  - "./reconfig_${_config}.sh"
  - "make -j$(nproc)"
  - "make check"
  # Make sure that all `#include` directives in our headers are met.
  - |
    for cmd in {"${CXX} -x c++ -std=c++98","${CXX} -x c++ -std=c++11"}; do
      echo "Checking #include directives using command:" $cmd
      $cmd -Wall -Wextra -Werror $(find src -name "*_generator.hpp" -prune -or -name "*.hpp" -print) -c /dev/null
    done

script:
  - "./makedeb.sh"

notifications:
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/#mcfproj"
    template:
      - "[ lh_mouse %{repository_slug}#%{commit}] %{result} on %{branch} by %{author} (%{build_url})"
  email: false
